### ISSUE TITLE
optimizations for sliceLeft

### ISSUE THREAD

**Issue by wishfoundry** [Skinney/elm-array-exploration#5]
I noticed that sliceLeft has multiple copy steps including
1. copy all leaves to a new list
2. resize list
3. reduce list back into a builder
4. stand up tree from builder list

At minimum, we could probably put a limit in the initial copy phase and save some initial work

I'm still a bit new to elm. I know it doesn't support looping in general, but is it kosher in elm to use an iterator? Theoretically I could eliminate much of the memory allocation, and possibly reduce the code down a bit to maybe:

```
sliceLeft from ((Array length _ tree tail) as arr) =
    initialize (.next (iteratorFor from, length, array) (length - from)
```

Additionally, if I wrote a native  Js iterable, one could eliminate the need to convert arrays when passing over ports.

**Comment by Skinney** [comment]
This is a good question, and if you have a good idea on how to do this in practice, I would love to hear it. I've attempted an iterator in the past, but the challenges boils down to the following:

1. Elm is a pure functional language. No side-effects allowed. This means that you can't just call `next` on an iterator and get the value back. You have to return a tuple with the value and the "new" iterator. This means boxing things in a tuple, and then unboxing it.

2. What happens when you call `next` at the end of an iterator? You'd probably have to return something to represent the empty case, which means wrapping the value in a `Maybe`. More unboxing. I guess you could crash in this case, but then you would need a `hasNext` fn. That's two function calls per element though.

3. An iterator does have some overhead. Since `Array` is a tree, you would need something like a zipper (current element, parent array).

Given the three things above, I'm not convinced that an iterator would be faster than just adding all leaves to a list (boils down to a nested for-loop). You're welcome to prove me wrong of course, but that is my reasoning for todays implementation.

**Comment by wishfoundry** [comment]
Your right in that iterators aren't entirely free. But they seem a good candidate for optimization.

If elm doesn't support the desired optimizations... then only remaining option seems do more of the work in native code.  But that begs some questions about what is the roadmap or driving goals here?

* is it an acceptable trade-off to maintain this in JS instead of elm if there are performance benefits?
* does coding this in native instead of elm affect elm's future goals, say for instance porting to web assembly?


Sorry if these seem a bit obvious. I just haven't any recorded discussion or guiding principle stated anywhere to know what direction makes sense.

**Comment by Skinney** [comment]
The goal of the project is to use as much Elm as possible. The problem with iterators isn't that they can't be implemented in Elm, but that they still has to be used from Elm. This means that it has to be immutable, and cannot have side-effects.

As I said, you are welcome to try an implementation for this. If it's faster,  I'll be happy to use it.
